package com.example.demo.service;

import java.util.Optional;

import com.example.demo.entity.User;
import com.example.demo.model.UserDto;
import com.example.demo.repository.UserRepository;

import org.springframework.stereotype.Service;
import jakarta.persistence.*;
import java.util.stream.Collectors;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
// no unused imports

@Service
public class UserServiceImpl implements UserService {
    private final UserRepository userRepository;

    // @Autowired removed
    public UserServiceImpl(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @Override
    public UserDto createUser(UserDto userDto) {
        User user = new User();
        user.setId(userDto.getId()); // Assuming ID is generated by the database
        user.setName(userDto.getName());
        user.setEmail(userDto.getEmail());
        User savedUser = userRepository.save(user);
        return new UserDto(savedUser.getId(), savedUser.getName(), savedUser.getEmail());
        
    }

    @Override
    public Page<UserDto> getAllUsers(Pageable pageable) {
        org.springframework.data.domain.Page<User> userPage = userRepository.findAll(pageable);
        java.util.List<UserDto> userDtos = userPage.getContent().stream()
                .map(user -> new UserDto(user.getId(), user.getName(), user.getEmail()))
                .collect(Collectors.toList());
        return new org.springframework.data.domain.PageImpl<>(userDtos, pageable, userPage.getTotalElements());
    }

    @Override
    public Optional<UserDto> getUserById(Long id) {
        User user = userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("User with id " + id + " not found"));
        Optional<UserDto> userDto = Optional.of(new UserDto(user.getId(), user.getName(), user.getEmail()));
        return userDto;
    }

    @Override
    public UserDto updateUser(Long id, UserDto userDto) {
        User user = userRepository.findById(id)
                .orElseThrow(() -> new jakarta.persistence.EntityNotFoundException("User with id " + id + " not found"));
        user.setName(userDto.getName());
        user.setEmail(userDto.getEmail());
        User updated = userRepository.save(user);
        return new UserDto(updated.getId(), updated.getName(), updated.getEmail());
    }

    @Override
    public void deleteUser(Long id) {
        if (!userRepository.existsById(id)) {
            throw new jakarta.persistence.EntityNotFoundException("User with id " + id + " not found");
        }
        userRepository.deleteById(id);
    }
}
